// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesmanager.proxies;

public class ProductFilterHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject productFilterHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SalesManager.ProductFilterHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PriceSelectedMinimum("PriceSelectedMinimum"),
		PriceSelectedMaximum("PriceSelectedMaximum"),
		ProductFilterHelper_Product("SalesManager.ProductFilterHelper_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductFilterHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SalesManager.ProductFilterHelper"));
	}

	protected ProductFilterHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productFilterHelperMendixObject)
	{
		if (productFilterHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SalesManager.ProductFilterHelper", productFilterHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SalesManager.ProductFilterHelper");

		this.productFilterHelperMendixObject = productFilterHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ProductFilterHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesmanager.proxies.ProductFilterHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesmanager.proxies.ProductFilterHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesmanager.proxies.ProductFilterHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesmanager.proxies.ProductFilterHelper(context, mendixObject);
	}

	public static salesmanager.proxies.ProductFilterHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesmanager.proxies.ProductFilterHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of PriceSelectedMinimum
	 */
	public final java.math.BigDecimal getPriceSelectedMinimum()
	{
		return getPriceSelectedMinimum(getContext());
	}

	/**
	 * @param context
	 * @return value of PriceSelectedMinimum
	 */
	public final java.math.BigDecimal getPriceSelectedMinimum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PriceSelectedMinimum.toString());
	}

	/**
	 * Set value of PriceSelectedMinimum
	 * @param priceselectedminimum
	 */
	public final void setPriceSelectedMinimum(java.math.BigDecimal priceselectedminimum)
	{
		setPriceSelectedMinimum(getContext(), priceselectedminimum);
	}

	/**
	 * Set value of PriceSelectedMinimum
	 * @param context
	 * @param priceselectedminimum
	 */
	public final void setPriceSelectedMinimum(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal priceselectedminimum)
	{
		getMendixObject().setValue(context, MemberNames.PriceSelectedMinimum.toString(), priceselectedminimum);
	}

	/**
	 * @return value of PriceSelectedMaximum
	 */
	public final java.math.BigDecimal getPriceSelectedMaximum()
	{
		return getPriceSelectedMaximum(getContext());
	}

	/**
	 * @param context
	 * @return value of PriceSelectedMaximum
	 */
	public final java.math.BigDecimal getPriceSelectedMaximum(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PriceSelectedMaximum.toString());
	}

	/**
	 * Set value of PriceSelectedMaximum
	 * @param priceselectedmaximum
	 */
	public final void setPriceSelectedMaximum(java.math.BigDecimal priceselectedmaximum)
	{
		setPriceSelectedMaximum(getContext(), priceselectedmaximum);
	}

	/**
	 * Set value of PriceSelectedMaximum
	 * @param context
	 * @param priceselectedmaximum
	 */
	public final void setPriceSelectedMaximum(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal priceselectedmaximum)
	{
		getMendixObject().setValue(context, MemberNames.PriceSelectedMaximum.toString(), priceselectedmaximum);
	}

	/**
	 * @return value of ProductFilterHelper_Product
	 */
	public final java.util.List<salesmanager.proxies.Product> getProductFilterHelper_Product() throws com.mendix.core.CoreException
	{
		return getProductFilterHelper_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of ProductFilterHelper_Product
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<salesmanager.proxies.Product> getProductFilterHelper_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<salesmanager.proxies.Product> result = new java.util.ArrayList<salesmanager.proxies.Product>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ProductFilterHelper_Product.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(salesmanager.proxies.Product.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of ProductFilterHelper_Product
	 * @param productfilterhelper_product
	 */
	public final void setProductFilterHelper_Product(java.util.List<salesmanager.proxies.Product> productfilterhelper_product)
	{
		setProductFilterHelper_Product(getContext(), productfilterhelper_product);
	}

	/**
	 * Set value of ProductFilterHelper_Product
	 * @param context
	 * @param productfilterhelper_product
	 */
	public final void setProductFilterHelper_Product(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<salesmanager.proxies.Product> productfilterhelper_product)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (salesmanager.proxies.Product proxyObject : productfilterhelper_product)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.ProductFilterHelper_Product.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return productFilterHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesmanager.proxies.ProductFilterHelper that = (salesmanager.proxies.ProductFilterHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SalesManager.ProductFilterHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
