// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesmanager.proxies;

public class ProductCategory
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject productCategoryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SalesManager.ProductCategory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CategoryName("CategoryName"),
		_Id("_Id");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProductCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SalesManager.ProductCategory"));
	}

	protected ProductCategory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject productCategoryMendixObject)
	{
		if (productCategoryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SalesManager.ProductCategory", productCategoryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SalesManager.ProductCategory");

		this.productCategoryMendixObject = productCategoryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ProductCategory.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesmanager.proxies.ProductCategory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesmanager.proxies.ProductCategory.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesmanager.proxies.ProductCategory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesmanager.proxies.ProductCategory(context, mendixObject);
	}

	public static salesmanager.proxies.ProductCategory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesmanager.proxies.ProductCategory.initialize(context, mendixObject);
	}

	public static java.util.List<salesmanager.proxies.ProductCategory> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<salesmanager.proxies.ProductCategory> result = new java.util.ArrayList<salesmanager.proxies.ProductCategory>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SalesManager.ProductCategory" + xpathConstraint))
			result.add(salesmanager.proxies.ProductCategory.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CategoryName
	 */
	public final java.lang.String getCategoryName()
	{
		return getCategoryName(getContext());
	}

	/**
	 * @param context
	 * @return value of CategoryName
	 */
	public final java.lang.String getCategoryName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CategoryName.toString());
	}

	/**
	 * Set value of CategoryName
	 * @param categoryname
	 */
	public final void setCategoryName(java.lang.String categoryname)
	{
		setCategoryName(getContext(), categoryname);
	}

	/**
	 * Set value of CategoryName
	 * @param context
	 * @param categoryname
	 */
	public final void setCategoryName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String categoryname)
	{
		getMendixObject().setValue(context, MemberNames.CategoryName.toString(), categoryname);
	}

	/**
	 * @return value of _Id
	 */
	public final java.lang.Long get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.Long get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.Long _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return productCategoryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesmanager.proxies.ProductCategory that = (salesmanager.proxies.ProductCategory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SalesManager.ProductCategory";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
