// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package salesmanager.proxies;

public class Sales
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject salesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SalesManager.Sales";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SalesId("SalesId"),
		SalesHeader("SalesHeader"),
		_Id("_Id"),
		Sales_Product("SalesManager.Sales_Product");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sales(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SalesManager.Sales"));
	}

	protected Sales(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject salesMendixObject)
	{
		if (salesMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SalesManager.Sales", salesMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SalesManager.Sales");

		this.salesMendixObject = salesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Sales.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static salesmanager.proxies.Sales initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return salesmanager.proxies.Sales.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static salesmanager.proxies.Sales initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new salesmanager.proxies.Sales(context, mendixObject);
	}

	public static salesmanager.proxies.Sales load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return salesmanager.proxies.Sales.initialize(context, mendixObject);
	}

	public static java.util.List<salesmanager.proxies.Sales> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<salesmanager.proxies.Sales> result = new java.util.ArrayList<salesmanager.proxies.Sales>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//SalesManager.Sales" + xpathConstraint))
			result.add(salesmanager.proxies.Sales.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SalesId
	 */
	public final java.lang.Long getSalesId()
	{
		return getSalesId(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesId
	 */
	public final java.lang.Long getSalesId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SalesId.toString());
	}

	/**
	 * Set value of SalesId
	 * @param salesid
	 */
	public final void setSalesId(java.lang.Long salesid)
	{
		setSalesId(getContext(), salesid);
	}

	/**
	 * Set value of SalesId
	 * @param context
	 * @param salesid
	 */
	public final void setSalesId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long salesid)
	{
		getMendixObject().setValue(context, MemberNames.SalesId.toString(), salesid);
	}

	/**
	 * @return value of SalesHeader
	 */
	public final java.lang.String getSalesHeader()
	{
		return getSalesHeader(getContext());
	}

	/**
	 * @param context
	 * @return value of SalesHeader
	 */
	public final java.lang.String getSalesHeader(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SalesHeader.toString());
	}

	/**
	 * Set value of SalesHeader
	 * @param salesheader
	 */
	public final void setSalesHeader(java.lang.String salesheader)
	{
		setSalesHeader(getContext(), salesheader);
	}

	/**
	 * Set value of SalesHeader
	 * @param context
	 * @param salesheader
	 */
	public final void setSalesHeader(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String salesheader)
	{
		getMendixObject().setValue(context, MemberNames.SalesHeader.toString(), salesheader);
	}

	/**
	 * @return value of _Id
	 */
	public final java.lang.Long get_Id()
	{
		return get_Id(getContext());
	}

	/**
	 * @param context
	 * @return value of _Id
	 */
	public final java.lang.Long get_Id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames._Id.toString());
	}

	/**
	 * Set value of _Id
	 * @param _id
	 */
	public final void set_Id(java.lang.Long _id)
	{
		set_Id(getContext(), _id);
	}

	/**
	 * Set value of _Id
	 * @param context
	 * @param _id
	 */
	public final void set_Id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long _id)
	{
		getMendixObject().setValue(context, MemberNames._Id.toString(), _id);
	}

	/**
	 * @return value of Sales_Product
	 */
	public final salesmanager.proxies.Product getSales_Product() throws com.mendix.core.CoreException
	{
		return getSales_Product(getContext());
	}

	/**
	 * @param context
	 * @return value of Sales_Product
	 */
	public final salesmanager.proxies.Product getSales_Product(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		salesmanager.proxies.Product result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sales_Product.toString());
		if (identifier != null)
			result = salesmanager.proxies.Product.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Sales_Product
	 * @param sales_product
	 */
	public final void setSales_Product(salesmanager.proxies.Product sales_product)
	{
		setSales_Product(getContext(), sales_product);
	}

	/**
	 * Set value of Sales_Product
	 * @param context
	 * @param sales_product
	 */
	public final void setSales_Product(com.mendix.systemwideinterfaces.core.IContext context, salesmanager.proxies.Product sales_product)
	{
		if (sales_product == null)
			getMendixObject().setValue(context, MemberNames.Sales_Product.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Sales_Product.toString(), sales_product.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return salesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final salesmanager.proxies.Sales that = (salesmanager.proxies.Sales) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SalesManager.Sales";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
